services:
  poll:
    container_name: poll
    restart: always
    build:
      context: ./poll
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - ${POLL_EXT_PORT}:${POLL_INT_PORT}
    networks:
      - poll-tier

  redis:
    container_name: redis
    restart: always
    image: redis:8.2-m01-alpine3.22
    env_file:
      - ".env"
    ports:
      - ${REDIS_EXT_PORT}:${REDIS_INT_PORT}
    networks:
      - poll-tier
      - back-tier

  result:
    container_name: result
    restart: always
    build:
      context: ./result
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - ${RESULT_EXT_PORT}:${RESULT_INT_PORT}
    networks:
      - result-tier
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:10
    container_name: postgres
    restart: always
    env_file:
      - ".env"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Paris
    ports:
      - ${POSTGRES_EXT_PORT}:${POSTGRES_INT_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - back-tier
      - result-tier
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    container_name: worker
    restart: always
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - 5002:80
    env_file:
      - ".env"
    networks:
      - back-tier
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  db-data:
    driver: local
